### ISSUE TITLE
DOC: Improve `main.ipynb` documentation

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#12]
## Tasks

- [x] Touch up the headers and divisions
- [x] Add better comments to each cell
- [x] Add overarching descriptions in markdown
