### ISSUE TITLE
ANA: Inter-facility transport

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#14]
## Questions

- [x] What is the method of transportation? (frequency table)
- [x] Where are they coming from? (location code frequency table)
- [ ] ANA: Inter-facility: Where are the patients coming from? Where are they going?
- [ ] ANA: Inter-facility: Who is doing the transportation?
- [ ] What portion of transportation is "Ground Critical Care Transfer"? (eDist.19 is Red or Yellow)

## Tasks

- [x] #15
- [x] Identify elements that would help answer the questions above
- [x] Determine which elements are in the database 
- [x] Load the available elements into one data frame
- [x] Exploratory data analysis -> add next steps

**Comment by Jython1415** [comment]
## Promising elements that are actually in the database

- eDisposition 20, 21, 22, 23
- eResponse 15, 23
- eScene 1, 9

**Comment by Jython1415** [comment]
dAgency_09 may be useful in figuring out who is doing the transportation

**Comment by Jython1415** [comment]
Page 22 (pg. 23 of the PDF) of the [2020 NEMSIS User Manual](https://nemsis.org/wp-content/uploads/2021/05/2020-NEMSIS-RDS-340-User-Manual_v3-FINAL.pdf) lists several variables that are not made available to the public. None of them are in the dataset that is available to me. However, three of the variables would be immensely useful in the analysis I would like to do.

```text
eResponse_01 EMS Agency Number
eResponse_04 EMS Response Number
eResponse_14 EMS Unit Call Sign
```

> This section includes the variable name and variable description for elements protected from public use in their native form. These variables can be made available as "de-identified data elements" (specified by the HIPAA Privacy Rule) by statistical manipulation to include masked anonymous value codes. Masked value codes can be grouped to address a specific hypothesis and made available to researchers through use of the master Primary Key (i.e., PcrKey) to link back to individual cases. Variable definitions and value codes can be found in the NEMSIS Data Dictionary (v.3.4.0) [https://nemsis.org/technical-resources/version-3/version-3-data-dictionaries/](https://nemsis.org/technical-resources/version-3/version-3-data-dictionaries/).

**Comment by Jython1415** [comment]
Reopen because this was not actually completed.

**Comment by Jython1415** [comment]
The remaining tasks of this issue should be broken up into ANA issues. I think it can be said that the primary objective of this issue, to start analysis of inter-facility transport, has been accomplished.

## Remaining Tasks

1.  Where are the patients coming from? Where are they going?
2. Who is doing the transportation?
3. What portion of transportation is "Ground Critical Care Transfer"? (eDist.19 is Red or Yellow)

(1) is not possible because that information is not included in the database. (2) is currently blocked because we do not have access to that data, but we are in the process of obtaining it (currently requesting). (3) can be done now.

- [ ] ANA: Transport agencies for inter-facility transport
- [ ] ANA: Frequency of Ground Critical Care Transfer
