### ISSUE TITLE
SPR: 2023-06-19

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#19]
Sprint for the week of June 19th, 2023

## Goals

- [x] Clean up previous code
- [x] Improve documentation
- [x] Minor logging improvements

Additional goals 🔽

- [x] Current analysis tasks
- [ ] Continue to improve documentation

## Issues

- [x] Jython1415/zoll-foundation-grant-project#16 
- [x] Jython1415/zoll-foundation-grant-project#15 
- [x] Jython1415/zoll-foundation-grant-project#12 
- [x] Jython1415/zoll-foundation-grant-project#8 
- [x] Jython1415/zoll-foundation-grant-project#10 
- [x] Jython1415/zoll-foundation-grant-project#11 
- [x] Jython1415/zoll-foundation-grant-project#9 
- [x] #13 
- [ ] #14 
- [ ] #20 
- [ ] #24 
- [ ] #25 
- [ ] #26 
- [ ] #27

**Comment by Jython1415** [comment]
Finished all the small issues in 1 day! I've got to add more to this task to make it a proper sprint for the week.

**Comment by Jython1415** [comment]
Updated tasks for the week given that I completed everything else before the week started.

## Goals

- [ ] Current analysis tasks
- [ ] Continue to improve documentation

## Issues

- [ ] #13 
- [ ] #14 
- [ ] #20 
- [ ] #24 
- [ ] #25 
- [ ] #26 
- [ ] #27

**Comment by Jython1415** [comment]
Need to make a new sprint issue and close this one.
