### ISSUE TITLE
DOC: Improve `tmp-table-management`

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#25]
## Tasks

- [ ] Write purpose of the notebook
- [ ] Clarify sections and actions
- [ ] Add a section to the wiki about using this notebook

**Comment by Jython1415** [comment]
Made the decision to depreciate this notebook because I am eventually going to depreciate the current usage of the "tmp" folder. Caching will also be managed by a dedicated module in zolltools (eventually) so this will become outdated. No need to improve it if is going to go unused.
