### ISSUE TITLE
DOC: Wiki page for location code groupings

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#31]
## Problem

The location code groupings are not well defined, and it is unclear where one can learn more about them.

## Tasks

- [x] Create a page to explain location codes and their groupings
- [x] Add an explanation for each of the existing location code groupings
  - [x] Suggested
  - [x] Health and other
  - [x] Inter-facility vs. Scene response depends on #29 
- [x] #42

**Comment by Jython1415** [comment]
Completed.
