### ISSUE TITLE
DOC: GitHub issue abbreviations

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#33]
## Tasks

- [ ] Figure out a good place for this. Maybe a developer guide in the wiki?
- [ ] Add an explanation
- [ ] Add an issue on [zolltools](https://github.com/Jython1415/zolltools) to do the same
