### ISSUE TITLE
ANA: `"Unknown"` values in `eScene_09`

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#79]
## Description

A careful analysis of `eScene_09` for ambulance transport revealed that a small number (~50) of ambulance transports have an `"Unknown"` location code instead of the null values specified by the data dictionary.

## Completion Criteria

- [ ] The source of these not values is determined

## Tasks

- [ ] Read `eScene_09` from the SAS file to determine if it is present there

**Comment by Jython1415** [comment]
Attempting download via the browser Box interface. If this fails, I will try FTP instead.

**Comment by Jython1415** [comment]
Downloading the SAS file using the Box interface worked, so I can proceed with reading eScene_09 information from this file.

**Comment by Jython1415** [comment]
The SAS file contains 51 occurrences of "Unknown"

- [ ] Confirm that the parquet file has the same number

**Comment by Jython1415** [comment]
This branch is related to #88, but will not be entirely resolved by it.

**Comment by Jython1415** [comment]
Both the SAS file and the parquet tables have the same number of "Unknown" values.

## Next steps

- [ ] Email NEMSIS to ask about this data
- [ ] Open the SAS table using SAS software to see if it is a software issue.

**Comment by Jython1415** [comment]
This was determined to be too minor of an issue to continue to pursue at the 2023-08-09 meeting. I may come back to it if there is a lot of extra time. Next steps for this task are the same as above. SAS analysis should come first!
