### ISSUE TITLE
ANA: Create manuscript-ready tables and figures

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zoll-foundation-grant-project#86]
## Description

The figures currently generated by the notebook needs to be cleaned up for the manuscript.

## Completion Criteria

- [x] Figures for location code analysis are manuscript-ready
- [x] Consider closing #46 in the meantime.

## Tasks

- [x] Find papers with nice figures and send to Andrew for review (get an idea of what to generate)
- [x] Determine what plotting package to use (Seaborn? Plain Matplotlib?)
- [x] Format figures

**Comment by Jython1415** [comment]
APA Guidelines:

- [APA - Figure Setup](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/figures)
- [APA - Sample Figures](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-figures)
- [APA - Accessible Use of Color in Figures](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/colors)

**Comment by Jython1415** [comment]
Update:

- Created drafts of manuscript-ready figures for the location code breakdown with #89 

Next:

- [ ] Clean up unused figures in the main notebook
- [ ] Prettify the remaining figures

**Comment by Jython1415** [comment]
Update:

- Finished cleaning figures with #104
